### ISSUE TITLE
`google/app-measurement`: Can't decode Protobuf

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/TrackHAR#10]
While working on https://github.com/tweaselORG/tracker-wiki/issues/3, I noticed that the `google/app-measurement` adapter fails to decode the Protobuf body.

Error:

```
/home/benni/tmp/abc/node_modules/trackhar/dist/index.js:3333
        else throw new Error("Protobuf input must be a byteArray or Uint8Array");
                   ^


Error: Protobuf input must be a byteArray or Uint8Array
    at $af1843b68b6e5fd0$export$2c626d165d0efff4 (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:3333:20)
    at Function.mergeDecodes (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:3447:20)
    at Function.decode (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:3405:21)
    at Object.decodeProtobuf (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:4001:77)
    at $149c1bd638913645$var$decodeRequest (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:4076:76)
    at $149c1bd638913645$export$c49bcb71aff21fdc (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:4085:28)
    at Array.map (<anonymous>)
    at $149c1bd638913645$export$e54fe5b0f43758f7 (/home/benni/tmp/noyb-demo/node_modules/trackhar/dist/index.js:4104:87)
    at <anonymous> (/home/benni/tmp/noyb-demo/data.ts:7:24)
```

The problem is that `input` is always a string, whereas the Protobuf decoder expects a byteArray or Uint8Array.

**Comment by baltpeter** [comment]
https://stackoverflow.com/a/45722000/3211062 has the answer: The problem is that our string has byte sequences that are not valid UTF-8.

And [`Buffer.from(string)` defaults to UTF-8 as the encoding](https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding).

Instead of the proposed solution in the answer, we can also simply use `Buffer.from(input, 'binary')`.
